name = "CoreMLProtobuf"
uuid = "a5f34d12-0067-4cbd-84e2-651e0174c66e"
authors = ["Tristian Azuara <tristian.azuara@gmail.com>"]
version = "0.1.0"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
julia = "1.3"
ProtoBuf = "0.11.1"
